apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-operator-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: "1.28.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg-operator
        namespace: flux-system
  interval: 1h0m0s
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
