apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: affine-staging
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: staging
  postBuild:
    substitute:
      release_name: "staging"
